### ISSUE TITLE
[Question] How are assemblies determined for module package?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#104]
When building the package with build.ps1, I get the usual expected laundry list of publish assemblies
![image](https://user-images.githubusercontent.com/15258962/78154239-df110000-73f0-11ea-94f4-a3ea5b98a4da.png)

However when the zip is made or nuget with dotnet pack, only the base assembly is included and there's no clear CI file in the repository.
![image](https://user-images.githubusercontent.com/15258962/78154663-5fcffc00-73f1-11ea-909f-64d9ee860e4f.png)

Which is different than the final assemblies found in the nuget package:
![image](https://user-images.githubusercontent.com/15258962/78154885-a02f7a00-73f1-11ea-8107-0f6808fa53e5.png)

How is it determined which assemblies should be included to be Powershell Standard (5.1-7) compatible?

**Comment by SydneyhSmith** [comment]
@JustinGrote as we mentioned we have not yet updated the build script, apologies for any lost time there! We determined which assemblies to include based off of reference assemblies that PowerShell (Core & Windows) didn't have, that we needed to reference at publish time. In other words, before we sign the package we remove those assemblies that are already in PowerShell, so that we are only distributing the assemblies that you need.

**Comment by JustinGrote** [comment]
@SydneyhSmith thanks, how do you determine these "included" assemblies? Just out of curiosity because I do it today by just pulling a list out of the directories as a static list :)

**Comment by alerickson** [comment]
@JustinGrote basically by comparing the assemblies published by PowerShellGet to the referenced assemblies that PowerShell already includes:
`[psobject].assembly.GetReferencedAssemblies()`

**Comment by JustinGrote** [comment]
@alerickson thanks, that's what I assumed, I just wasn't sure if there was some sort of manifest that exists for this sort of thing.
