### ISSUE TITLE
Find-PSResource -IncludeDependencies should deduplicate the dependencies.

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#109]
### Steps to reproduce
`find-psresource az -includedependencies`

### Result
![image](https://user-images.githubusercontent.com/15258962/78710205-c8bfe400-78c9-11ea-972f-e3793b82dcbe.png)

### Expected
Should only see one instance of Az.Accounts per version found, not have it repeated.

### Workaround
`Find-PSResource az -IncludeDependencies | sort name,version -unique`

**Comment by SydneyhSmith** [comment]
Confirm that this issue is still occurring

**Comment by JustinGrote** [comment]
This article covers how to use NugetResolver to deduplicate dependencies under section "RESOLVE THE DEPENDENCY GRAPH FROM THE LIST OF AVAILABLE PACKAGES"
https://martinbjorkstrom.com/posts/2018-09-19-revisiting-nuget-client-libraries

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.

**Comment by JustinGrote** [comment]
@alerickson FYI if you add a commit that fixes it, you can simply reference this issue in the commit message or PR message, e.g. "fixes #109", that way there is an automatic link to *where* you fixed it so I can review, rather than guessing where this was resolved and not being able to provide further feedback

https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by alerickson** [comment]
Ideally I'd like to close the issue with the PR it was fixed in but we weren't great about filtering through issues and doing that as PRs were opened and merged in.  Right now I'm just trying to go through and validate which issues are fixed and clean up our [Preview 11 project](https://github.com/PowerShell/PowerShellGet/projects/10#card-66194283).  I'll come back and add the PRs they were fixed in though.
