### ISSUE TITLE
File path version must match psd1 version when publishing

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#1106]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Publish-PSResource: Error occured while running 'Test-ModuleManifest': The ModuleVersion key in module manifest 'C:\Users\pmeinecke\Woot\1.0.0\Woot.psd1' specifies module version '1.0.1' which does not match its version folder name at 'C:\Users\pmeinecke\Woot\1.0.0'. Change the value of the ModuleVersion key to match the version folder name.

Since you need to specify the psd1 anyway, this check feels like it maybe shouldn't be needed. Might not be easily able to separate though and shouldn't be too impactful

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
N/A
```

**Comment by SydneyhSmith** [comment]
The psd1 should be the source of truth since once the file leaves your box and is published the path it was at originally is irrelevant, in fact I agree that we really dont need to be checking it in the first place 

Test-ModuleManifest is coming from PowerShell so it is the one checking this, but I think we should ignore the error
