### ISSUE TITLE
PowerShellGet shipping in PowerShell 7.4 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#1120]
### Summary of the new feature / enhancement

- PowerShellGet v3 (`-PSResource cmdlets`) will be renamed to PSResourceGet begining with the next release (beta22).
- PowerShell v7.4 (LTS) will ship PSGet v2.2.5 and PSResourceGet v3.0.x. This will help us get telemetry about usage of PSResourceGet. No compat layer will be shipped. This allows current scripts to work as is, with or without fully qualified cmdlet names.
- Customers can use `-PSResource` cmdlets for perf improvements and new features. No new feature work will be done in `-Module` cmdlets.
- In the first preview of PowerShell v7.5 we include [CompatPowerShellGet](https://www.powershellgallery.com/packages/CompatPowerShellGet/0.0.4) renamed as  PowerShellGet v3.0.0 in addition to PSResourceGet. In PowerShell v7.5 we will not ship PowerShellGet v2.2.5 side by side.
- We will get feedback from community about the compat layer which will help use decide on our future course.
- When time comes, we ship PSResourceGet in addition to current PowerShellGet 1.0.0.1 in Windows PowerShell.
- We will also work with Windows to improve the current Install/Upgrade experience in Windows PowerShell.

**Comment by ThomasNieto** [comment]
Since you're going to renaming the module will you be putting it in the Microsoft.PowerShell module prefix?

**Comment by SydneyhSmith** [comment]
> Since you're going to renaming the module will you be putting it in the Microsoft.PowerShell module prefix?

Yeah, we like that idea

**Comment by ThomasNieto** [comment]
I just thought of this, what to you think about keeping the PowerShellGet name but with the prefix?

Microsoft.PowerShell.PowerShellGet

**Comment by ajansveld** [comment]
I think the Microsoft.PowerShell.PSResourceGet rename (and shipping it side-by-side) is a great idea, but at that point can we also just drop the "Get" part? Seems to make sense since:
- The name is inconsistent with general module naming practices
- The module does more than "get"
- (Most of) the cmdlets have the PSResource prefix

Vote for `Microsoft.PowerShell.PSResource`!

**Comment by SydneyhSmith** [comment]
For reference this is our current list of "breaking changes" with the compat layer: 

Breaking Changes:
- proxy support not supported yet
- New-ScriptFileInfo and Update-ScriptFileInfo had -PassThru, in v3 there's no passthru, but we write file contents to the console
     + possible solution is to do 'New-PSScriptFileInfo', then use 'Get-PSScriptFileInfo'
- whatif and confirm not supported for update-psscriptfileinfo right now
- Filter no longer exists for Find cmdlets
- Remove 'SkipPublisherCheck'  in v3 we now have 'AuthenticodeCheck'
- For now v3 will always clobber 
- No more 'NoPathUpdate' parameter for Install-Script
- Publish-Module now no longer takes the following parameters (ie they are now no ops):
       Name
       RequiredVersion
       FormatVersion
       ReleaseNotes
       Tags
       LicenseUri
       IconUri
       ProjectUri
       Exclude
       AllowPrerelease
       SkipAutomaticTags
- No longer support 'LiteralPath', just 'Path' (for every cmdlet)
- Repository (register, set) no longer take 'Credential' because it no longer pings the uri
- Register, set no longer accepts the following params:
    PublishLocation
    ScriptSourceLocation
    ScriptPublishLocation
    PackageManagementProvider
- Wherever parameters are no longer accepted, the compat module will still bind them and then just delete them
- Save will now by default accept license

**Comment by ThomasNieto** [comment]
When the module is renamed, the version should be reset. I'd recommend starting with 0.x.x during preview releases and when GA happens 1.0.0. This allows users to install the preview versions easier without having to use `-Prerelease` and has the added benefit of allowing modules to have dependencies on `PSResource`.

**Comment by alerickson** [comment]
We were going back and forth on what to do for the version of the new module.  The current thought was to start PSResourceGet at version 3.x, primarily for documentation purposes-- we would have PowerShellGet v3 bundled as PSResourceGet and PowerShellGet (ie the compat layer).  I think there was some concern in terms of branding too, ie "PSResourceGet v3" might be more easily be seen as a name change of "PowerShellGet v3" as opposed to PSResourceGet v1.  However, the more I think about it, the more I think it'd be nice to have a clean break and start fresh, so to speak.

**Comment by alerickson** [comment]
Linking this PR: https://github.com/PowerShell/PowerShell/pull/19597/files

**Comment by SydneyhSmith** [comment]
# Some updates 

These are our most up to date plans, please let us know any feedback or concerns 

## Module Versions 

 - PowerShellGet 3.0.beta22 == CompatPowerShell preview 5
  - When we ship that we can deprecate Compat
  - GA of compat will be PowerShellGet 3.0.100, this will be by PowerShell 7.5 preview 1 (early Dec 2023 time frame)
  - PSResourceGet preview will be 1.0.1-preview or 0.0.1-preview
  - GA will be 1.0.100 or 1.0.0
  - First servicing will be 1.0.101 or 1.0.1
 
We are deciding between these two versioning strategies for PSResourceGet, if you have a preference please let us know. 

## Module GUIDs

  - All previous versions of PowerShellGet have same GUID so should stay same for  PowerShellGet 3.0.beta22 which == Compat
  - PSResourceGet will have a new GUID
 
## Naming Timing 

Not a promise but current plan is to start making naming changes in the repo on Tuesday May 30th (this is always subject to being pushed out 😄 ), the next release will be under the new name and will ship in PowerShell, to see what is expected to ship in this release check out this project https://github.com/PowerShell/PowerShellGet/projects/21

**Comment by ThomasNieto** [comment]
I'd just recommend using the standard semver scheme and starting with 1.0.0 for GA of `PSResource` (note: I left off `Get` 😉).

**Comment by kilasuit** [comment]
If you are renaming then logically `GetPSResource` would make more sense than `PSResourceGet` but just `PSResource` makes sense too 

Also, because I'm lazy (like most when possible) and don't want to waste what [keys I have left](https://www.keysleft.com/) I really don't see the need for the `Microsoft.PowerShell` prefix to the name of the module, when internally to it that makes sense as a namespace but isn't as needed in PowerShell as it is in C# especailly as there are methods that we can already identify the author from the PSD1 of the module.

Also Fully Qualifying this to `Microsoft.PowerShell.PSResourceGet\Get-PSResource` is as above more painful than `PSResource\Get-PSResource`

Whilst the Verboseness of `Microsoft.PowerShell.PSResourceGet\Get-PSResource` is something some may like we get far too many complaints generally in the community of PowerShell sometimes being overly & unnecessarily Verbose 

Even cutting `Microsoft.PowerShell.PSResourceGet\Get-PSResource` to `Msft.Pwsh.PSResource\Get-PSResource` (If a prefix to the module name is deemed needed still as a wider across PowerShell as a whole) would be a good step forward even if that is a break in expectation from other Modules shipped so far - this may also help with one of @SteveL-MSFT discussions about a PSv2 mode as could ship existing and new versions and require module qualifying to be used to ensure getting new experience over old. I know that's a discussion outside of this issue but it seems worthy bringing it up whilst PowerShellGet is going through what is a similar transition in functionality.

But if it's a case of `PSResource` vs `GetPSResource` vs `PSResourceGet` I'm more inclined on either of the first 2 & personally would rather miss out a prefix before it, but understand why the team may want keep one.

I know this _may_ be too late to do anything about it but I just wanted to get these points down **hopefully before** it's to late for the team to consider them

Also +1 on SemVer for versioning as that's what generally is trying to be used elsewhere (both internal & external to the PowerShell/dotnet ecosystems) from what I've seen

**Comment by ThomasNieto** [comment]
The core modules have had the Microsoft.PowerShell prefix since the beginning. Only the side projects that got added later like PSReadLine didn't have the prefix. If you look at the [gallery](https://www.powershellgallery.com/packages?q=microsoft.powershell) all the PowerShell team's side projects have had that prefix for a while now. I believe the team has done that when the gallery adds prefix reservations like nuget.org so users at a glance would know this is an official Microsoft module. As of right now anyone can create a module in that name space. Look at `PS` prefix as an example, that was supposed to be reserved for the PowerShell team but everyone uses that for their modules and cmdlets.

While I agree with you that every character typed hurts user experience I beg to differ that a normal end user will have a built-in module as a hinderance with module auto-loading or tab completion. The only time they would need to use the full module name is to install it or module qualifying. For the module qualifying issue, the user experience for that workflow is not great to begin with and have proposed removing that barrier in this https://github.com/PowerShell/PowerShell/issues/19657#issuecomment-1553050478

And for the module name, I don't know if there is an unwritten rule that Microsoft package managers (OneGet, PowerShellGet, WinGet, NuGet) have to include `Get` as a suffix but its not needed, PSResource is just fine.

**Comment by SteveL-MSFT** [comment]
@ThomasNieto is correct that all the modules that originated from the PowerShell team as a Microsoft project are properly (and required) namespaced.  PSReadLine, as noted, started as a side project (and there are some other examples) which retain the unnamedspaced name.  It is our intent in the future to have namespaces in PowerShellGallery as this not only avoid name conflicts, but also prevents squatting such that you know a module came from Microsoft, Amazon, etc...

Also, as Thomas noted, the `Get` suffix has precedent to indicate a package manager while `PSResource` seems like it would just be a single resource.

The feedback is appreciated, however, I don't think there's any compelling reason to not move forward with our current naming plan.

**Comment by ALIENQuake** [comment]
The initial post contains `PSGet`, why it wasn't considered for a new name? I fit so nicely with OneGet, WinGet, NuGet, etc.
