### ISSUE TITLE
Find-PSResource Nuget Version Range Exclusive Upper Bound does not work

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#119]
![image](https://user-images.githubusercontent.com/15258962/79176399-f8cd2280-7db4-11ea-9c18-f0a22198fde7.png)

The first command should return nothing since it is an exclusive upper bound

Reference: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by SydneyhSmith** [comment]
@JustinGrote thanks for the feedback, just want to clarify...the Pester Version which gets returned is 
4.10.0 which I would understand to be the latest version less than 4.10.1 (since using the "exclusive" parenthesis) which is returned in the second case, with the "include" bracket....is that what you are expecting?

**Comment by JustinGrote** [comment]
@SydneyhSmith I think I must have misread or goofed on this one, I was having it return nothing previously but looking at my own screenshot seems to be fine.

I can't reproduce now so chalk it up to a weirdness on my side, will close unless I can repro.
