### ISSUE TITLE
Publish-PSResource omits some metadata when publishing scripts

### ISSUE THREAD

**Issue by peetrike** [PowerShell/PSResourceGet#1243]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

when publishing script with Publish-PSResource, the resultant .nupkg file does not have included the following elements:

- licenseUrl
- projectUrl
- releaseNotes
- dependencies

### Expected behavior

```console
all metadata is included
```

### Actual behavior

```console
abovementioned metadata is missing for resultant package
```

### Error details

```console
no errors
```

### Environment data

```powershell
Powershell: 5.1, 7.3.5
PSResourceGet: 0.5.22
```

**Comment by peetrike** [comment]
as with #1220, this problem was caused by comma in script metadata field ExternalModuleDependencies module list.  After removing comma, all metadata was published.

**Comment by anamnavi** [comment]
@peetrike thanks for bringing this issue to our attention! 

I'm having a little trouble reproducing this...do you mind sharing some info?

* How did you create the script? Manually or with `New-PSScriptFileInfo`? I tried reproducing this with `New-PSScriptFileInfo -ExternalModuleDependencies "dep1","dep2"` and it populates that metadata in the .ps1 file without a comma like so: `.EXTERNALMODULEDEPENDENCIES dep1 dep2`

* Which repository are you publishing to? To PSGallery, a local repo or some other repo?

* If you can share the contents of your .ps1 file that's great, otherwise can you share what values you have for the `ExternalModuleDependencies` (with the comma and without that worked per your issue details)?

**Comment by peetrike** [comment]
The problematic script was years old script that was used by PowerShellGet.  For understanding, what's wrong, I started to create new scripts.

New-PSScriptFileInfo creates correct metadata.

**Comment by peetrike** [comment]
Maybe I must clarify, that I checked .nuspec file inside published .nupkg.  If that file is not used by `Find-PSResource`, then it might not be a problem, if that file has some elements missing.

**Comment by peetrike** [comment]
I added all my test scripts to https://github.com/peetrike/Examples/tree/main/src/quirks/PSResourceGet .   Feel free to use them, if it helps.
