### ISSUE TITLE
[Find-PSResource] the parameter -Prerelease do not works when a local PSRepository exist

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PSResourceGet#1290]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1 - Create a local repository ( file system) with the name 'PSAaron'  with a priority  40 ( default PSGallery 50)
2 - Publish one prerelease version of a module 'String' into 'PSAaron' repository
3 - Use
```powershell
Find-PSResource -Name 'String' -Prerelease -Repository PSAaron
```
Note : in PSGallery there is already a module with the same name 'string' with different versions than those existing in the local repository. But the two manifests have different module GUIDs.

This request return a correct result :
```powershell
Find-PSResource -Name 'PnP.PowerShell' -Prerelease -Repository PSGallery

Name           Version Prerelease Repository Description
----           ------- ---------- ---------- -----------
PnP.PowerShell 2.2.26  nightly    PSGallery  Microsoft 365 Patterns and Practices PowerShell Cmdlets
```
But not this :
```powershell
Find-PSResource -Name 'String' -Prerelease -Repository PSGallery

Name   Version Prerelease Repository Description
----   ------- ---------- ---------- -----------
string 1.1.3              PSGallery  Module to execute script operations
```

### Expected behavior

```console
Find-PSResource -Name 'String' -Prerelease -Repository PSAaron

Name   Version Prerelease Repository Description
----   ------- ---------- ---------- -----------
String 1.1.0   beta       PSAaron    Module String
```

### Actual behavior

```console
Find-PSResource -Name 'String' -Prerelease -Repository PSAaron

Name   Version Prerelease Repository Description
----   ------- ---------- ---------- -----------
String 2.0.0              PSAaron    Module String
```

### Error details

```console
no error record.
```

### Environment data

```powershell
Get-Module Microsoft.PowerShell.PSResourceGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.22     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceR...


$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3031}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/b504f961-1a1f-40f9-aea0-5ef76ec49fee)

![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/394737ee-0bdd-4e9a-b1ab-982733b0e2d0)

![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/54b4ddd0-b320-46d4-9f1f-88460e4ba941)

**Comment by alerickson** [comment]
Hi @LaurentDardenne,  we took a look at this issue and think that everything is occurring as expected.  

The `-Prerelease` parameter is inclusive in the sense that if the latest version is a prerelease it will show that particular version, but if the latest version is not a prerelease, it will still display that latest version.  

So, if the module 'String' has versions 1.1.0 beta and 2.0.0, passing in the `-Prerelease` parameter will return the same results.  However, if 'String' had versions 1.1.0-beta, 2.0.0, and 3.0.0-beta, the following would happen:

``` powershell
Find-PSResource -Name 'String' -Prerelease -Repository PSAaron

Name   Version Prerelease Repository Description
----   ------- ---------- ---------- -----------
String 3.0.0   beta       PSAaron    Module String


Find-PSResource -Name 'String' -Repository PSAaron

Name   Version Prerelease Repository Description
----   ------- ---------- ---------- -----------
String 2.0.0              PSAaron    Module String


```


I'm going to close this issue as expected behavior, but feel free to comment if there's questions or concerns regarding this behavior.

**Comment by anamnavi** [comment]
@LaurentDardenne thanks for reaching out and the thorough examples!

This is by design, when running `Find-PSResource` with `-Prerelease` it will return the latest version (and it will consider all versions including **both** stable and preview). Without `-Prerelease` it'll return the latest stable version only. Since you're using the `-Prerelease` parameter and the latest version for the `String` package is 2.0.0 in the PSAaron repository (including stable and preview versions and 2.0.0 is higher than 1.1.0-beta), you will get back 2.0.0.

If you would like 1.1.0-beta back, I'd suggest something like `Find-PSResource -Name "String" -Version [, 2.0.0) -Prerelease` perhaps? :)

**Comment by LaurentDardenne** [comment]
Thank you, I had not understood this behavior.

>>when running Find-PSResource with -Prerelease it will return the latest version

In fact the underlying need is to know the last stable version or the last prerelease version or the last published version, by searching in all the repositories.

The design for the search, which by default stops at the first priority repository, does not facilitate exploration, I find.
I have the impression that I have to know the existing to search for a resource, whereas the search should allow me to know the existing.
But it's an other problem.
