### ISSUE TITLE
[Question] Install-Module partially installs

### ISSUE THREAD

**Issue by VaughanJ** [PowerShell/PSResourceGet#147]
We have a reasonably large build and deployment library built around Powershell modules. In the last few months I have seen a few times that we have a module or it’s dependent modules partially installed. I say partially installed, but it could also be partially uninstalled.

I think it’s an installation issue as one module has the following files/folders installed:

- PSD1
- PSM1
- Private folder containing all the scripts
- Public file (This should be a folder containing scripts) **This is the point of concern**

Another installation of AWSPowershell (which we have as a dependency of our modules) contained just the PSD1 and no other files.

The above two lead me to believe it’s an installation issue rather than anything else.

However; This issue is very sporadic, so recreating it is near impossible. I have written a few scripts with loops installing modules and importing, another script in a different session uninstalling and can't create. These scripts have been run in various combinations; again with no luck recreating the issue.

My question are:

- Has there been any known issues around the area of partial installs of modules?
- What's the best way to track this issue down?
- Does PowershellGet download the package to a temporary location and then move to the module directory? and if so could it have failed here?
- If it's not an install issue, maybe it's an uninstall issue, have there been similar bugs around this area?

ModuleType Version    Name                                ExportedCommands                                                           
---------- -------    ----                                ----------------                                                           
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}               
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

**Comment by SydneyhSmith** [comment]
@VaughanJ thanks for opening this issue, partial uninstallation is an issue we have had reported before particularly in the case of large, nested modules (like the Az module)... what sometimes happens is that a module cannot be fully uninstalled because some of the files may be loaded/in use...if this is the case the user should be prompted with an error message/warning although we have had reports that this may not be the case at times...this is an issue we hope to address in PowerShellGet 3.0 our next major version release.

If you find a successful repro that would also be very helpful to us verifying this is the issue at play. Thanks!

**Comment by SydneyhSmith** [comment]
Closing as we have added the additional verbosity in Install to try and address this issue
