### ISSUE TITLE
Adding the Parameter -Credential to Register-PSResourceRepository

### ISSUE THREAD

**Issue by tinuwalther** [PowerShell/PSResourceGet#1669]
### Summary of the new feature / enhancement

As a user of the PSResourceGet module I want to pass a PSCredential object (username and password) as it is possible in the PowerShellGet module, because I cannot install the Microsoft.PowerShell.SecretManagement module without a registered repository or/and without an internet connection to the PowerShell Gallery.

### Proposed technical implementation details (optional)

It should be possible to use the Register-PSResourceRepository as in the following example:

````powershell
[PSCredential]$cred = Get-Credential -Message 'Enter your credentials for the repository to register'

$parameters = @{
    Name = 'nexusNugetRepo'
    Uri  = 'http://localhost:8081/repository/PSModules/'
    Trusted = $true
    Priority = 50
    Credential = $cred
} 
Register-PSResourceRepository @parameters 
````

**Comment by tinuwalther** [comment]
@alerickson I discussed this with you at the PSConfEU in Antwerp at your session on container galleries

**Comment by SydneyhSmith** [comment]
Basically this is not required because while PowerShellGet pinged the uri at registration time, PSResourceGet does not-- therefore you can pass in the -Credential using the -Credential param at Install-PSResource time... the reason that credential persistence is not supported without SecretManagement is because there is no SecretVault to securely keep the credential in... perhaps a reason to ship SecretManagement in PowerShell 7.x
