### ISSUE TITLE
Black Lives Matter

### ISSUE THREAD

**Issue by whatsthedealwithpolitics** [PowerShell/PSResourceGet#181]
My previous post regarding this matter was closed as "Off-Topic".  Per your contact page, website issues are to be posted to your GitHub: https://www.powershellgallery.com/policies/Contact

This is a website issue.  The top of your website states "Black Lives Matter".  I am posting here at the direction of those with the authority to authorize changes on your website.  So, kindly do not close this post against their wishes.
---
Your FAQ directed website issues to GitHub, and I feel its appropriate for your organization to publicly respond to your public advocacy.
Black Lives Matter is a political organization attempting to advance a communist / marxist / socialist agenda. I presume Microsoft is already aware of truths regarding behind the organizations which they support and have either chosen to accept them or be willingly ignorant toward them. All Lives Matters goes without saying as much as Black Lives Matter goes without saying, as well as various other racial or ethnic groups, I merely question the politicization and weaponizing of "PowerShell Gallery" against the founding principles of Microsoft's own founding country.
Is Microsoft's public stance now to openly oppose our founding principles and to advocate for political parties -- or is it to develop software and tools?
Please provide clarification on the political advocacy on "PowerShell Gallery"

**Comment by alerickson** [comment]
Hi @whatsthedealwithpolitics this issue is off-topic to PowerShellGet.  As per the contact page you linked to:

> If you're having trouble with the https://www.powershellgallery.com Website, file a bug on the PowerShell Gallery Issue Tracker. If you're having trouble with the PowerShellGet, file a bug on the PowerShellGet Issue Tracker.

Feel free to open the issue in the[ PowerShell Gallery repository](https://github.com/PowerShell/PowerShellGallery), but as previously mentioned, Microsoft's official stance is conveyed in[ this blog post](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.microsoft.com%2Fblog%2F2020%2F06%2F23%2Faddressing-racial-injustice%2F&data=02%7C01%7CAmber.Erickson%40microsoft.com%7C756f928167f64ad25d5008d827413ea2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637302508462499247&sdata=GhiMHWgssS8gvXHTM17bsUQjQaCRCk31Vdw%2BYpfectg%3D&reserved=0).
