### ISSUE TITLE
Document Proxy support

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#244]

**Comment by alerickson** [comment]
we should not implement the parmas right now and encourage users to configure this setting themselves, either through an environment variable or by modifying their nuget.config file.

The two implementations I was looking at were 1) modifying the process environment variable or 2) modifying the user's nuget.config file.

1) Initially modifying the environment variable seemed like the best route to take, but after doing more thorough research, it seems like a lot of folks have had issues configuring the value and getting NuGet to read it properly. NuGet has very little documentation here, but it looks like the `http_proxy` variable is one that's widely used and typically takes one of the following formats:
`http://<proxy>`
`http://<proxy>:<port>`
`http://<username>:<password>@<proxy>`
`http://<username>:<password>@<proxy>:<port>`
PSGet would need to do a lot of manipulation to get this configured properly. There's a lot of points of failure here which is concerning, especially given that there's no direct guidance on how this should be set up, and no easy way to thoroughly test scenarios. I can see this being a point of frustration and inconsistently working (ie working for some users but not others), which makes me hesitant.

2) Modifying the nuget.config file, seems to be a more reliable way to configure a proxy because we're adding a proxy key (which can include port number), adding a username key, and adding a password key, all as separate variables that are easily modifiable by the user since we store what's directly passed in from the user.  The primary issue with this implementation is that there's a potential security vulnerability with PSGet writing passwords to the nuget.config file. This implementation also feels a bit hacky.

What we'd like to do is encourage users to configure proxies themselves and if we get feedback that it's too frustrating or they need a smoother experience, we can come back to one of these implementations. The big todo here now is clear documentation on how users can properly set up one of these two configurations.

**Comment by alerickson** [comment]
The above two linked PRs show an implementation for the two options.

**Comment by sdwheeler** [comment]
It looks like `Publish-PSResource` is the only cmdlet that has proxy parameters.
