### ISSUE TITLE
Publishing with publish-psresource requires specific folder name [3.0.0-beta10]

### ISSUE THREAD

**Issue by adrian-andersson** [PowerShell/PSResourceGet#305]
When using publish-psresource, the folder/directory name must be the same as the directory folder, and publishing from a folder with the version name will result in an error

Example:
```
gh:\psrapid\psrAPId> publish-psresource -path C:\Users\adrian.andersson\git\psrapid\psrAPId\1.0.1\psrAPId.psd1 -Repository powershellgetbeta -Credential $pshelf.credential -APIKey $pshelf.NuGetApiKey -verbose
Publish-PSResource: Value cannot be null. (Parameter 'path')
[14:28 | 0.02]
gh:\psrapid\psrAPId> publish-psresource -path C:\Users\adrian.andersson\git\psrapid\psrAPId\1.0.1\ -Repository powershellgetbeta -Credential $pshelf.credential -APIKey $pshelf.NuGetApiKey -verbose
Publish-PSResource: No file with a .psd1 extension was found in C:\Users\adrian.andersson\git\psrapid\psrAPId\1.0.1\1.0.1.psd1.  Please specify a path to a valid modulemanifest.
```

Works fine if the folder name matches the psd1 name. Seems its parsing the folder name and searching for a manifest file using that name, which makes having a versioned release folder a bit more complicated

Bonus Oddness:
It is possible to omit the repository name and publish-psresource will not throw an error, even if there are multiple repositories with the same priority weight

**Comment by SydneyhSmith** [comment]
Thanks @adrian-andersson is this a publishing pattern that you had used in the past with older versions of PowerShellGet? 

In terms of the "bonus oddness" this was a design we made by design based on user feedback that it was a frustrating experience to not have a repository selected if one was not specified---we are open to more feedback on this issue if this behavior should only apply to install and not to publish--thanks!

**Comment by adrian-andersson** [comment]
Hi @SydneyhSmith we publish our modules with a framework - specifically this: https://github.com/DomainGroupOSS/bartender

I can see _why_ you would do this since there is no parameter for module name in the psd1 manifest, but would it not make more sense to use the filename of the psd1 instead? Or is your concern that a directory might contain multiple psd1 files, so assume that the psd1 file with the same name as the containing folder is the correct file to reference?

Maybe we can get a compromise solution with the -path variable, where you can provide a folder path and stick to your existing behaviour, or you can provide a psd1 and use the psd1 filename.

**Comment by mgreenegit** [comment]
Confirmed. Repro:
Module file name - AzureConnectedMachineDsc.psd1
Publish-PSResource -ApiKey '***' -Repository PSGallery -Path '/Users/username/git/AzCMAgentPublish/' -Verbose
Publish-PSResource: Value cannot be null. (Parameter 'path')

I was using a different folder name because I don't want to publish every file I use in my local testing/development folder.

It doesn't seem like a good practice to require assumptions about the folder name/structure. At minimum, the error message does not indicate what the user needs to do, so that could be corrected.

**Comment by JustinGrote** [comment]
I would suggest that, if I point my publish directly to a .psd1, you can make many assumptions off that:
1. The module name is the same as the .psd1 filename (since thats how modules work)
2. The folder of that .psd1 is the root of the module

So have special logic for pointing to a .psd1 directly, otherwise you can enforce the typical conventions for "looking" for a module if I specify a folder instead.

**Comment by Jaykul** [comment]
It's broken the other way too. I used to publish with folder name:

```PowerShell
Publish-PSResource -Path C:\Users\Jaykul\Projects\Modules\TerminalBlocks\1.0.0
```
Now it expects the file to be named 1.0.0 instead of "TerminalBlocks.psd1":
```
Publish-PSResource: No file with a .psd1 extension was found in C:\Users\Jaykul\Projects\Modules\TerminalBlocks\1.0.0\1.0.0.psd1.  Please specify a path to a valid modulemanifest.
```
