### ISSUE TITLE
Ensure installed module permissions for AllUsers allow all users to read/execute

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PSResourceGet#364]
From https://github.com/PowerShell/PowerShell/issues/15330.

That issue is around PSGet v2 and particularly PackageManagement, but @PaulHigin asked me to open an issue here.

Essentially module files (and a temp directory) were being created by PSGet on Ubuntu 20.04 with the other user permissions set to none (octal permissions `1750`), meaning that other users (all users) couldn't read or execute the installed modules.

Instead, the needed permissions were `1755`.

PowerShellGet should ideally validate itself that the appropriate permissions are set for modules installed in a given scope; it should either set the permissions to be the correct ones, or throw an error that the module can't be installed correctly.

**Comment by JamesWTruher** [comment]
I'm not sure the sticky bit needs to be set for this directory (although it probably doesn't hurt). Permissions of 0755 should be ok as well..

**Comment by jocobwknight** [comment]
If somebody runs across this because they're trying to:
- get an installed module to run as a non-root user
- on PowerShell-Core (v7.1.3)
- on a RedHat Linux system (v7.8)
- and it seems to install just fine with `Install-Module -Scope "AllUsers"`
- and it seems to run just fine when you enter pwsh as _root_

**THEN** you may be on the same Google journey that I've just been on, and I can open up a shortcut for you:

[Issue 457](https://github.com/PowerShell/PowerShellGetv2/issues/457) has a post by [RobCannon](https://github.com/RobCannon) with a workaround that worked for me (after some accounting for my situation):
```bash
# After uninstalling the modules and PowerShell itself completely, starting from a clean slate...
curl -s https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
sudo -- sh -c 'umask 002; yum install -y powershell'
sudo pwsh
Set-PSRepository -Name "PSGallery" -InstallationPolicy "Trusted"  # If you're installing a module from PSGallery...
Install-Module -Name powershell-yaml -Force -Repository PSGallery -Scope "AllUsers"  # Just using this as an example
Exit
sudo chmod 755 -R /usr/local/share/powershell
```

This worked for me for `PowerCLI` and `powershell-yaml`, which are the only ones I needed. Hope this helps!

**Comment by StevenBucher98** [comment]
Seems when I was testing with my Ubuntu on Windows it seems most module folders are with user permissions 0777 which seems to have more permissions than 0755, will be keeping in mind as we introduce scope parameters in PowerShelLGetv3

**Comment by alerickson** [comment]
Can confirm, also getting 0777.  Going to close this since it does not seem to be an issue with v3 :smiley:
