### ISSUE TITLE
-RequiredVersion should not also need -AllowPrerelease

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#43]
Creating an issue to track this request from twitter: 
https://twitter.com/Jaykul/status/1060667872735834112 

On Install-Module, if -RequiredVersion is used, the -AllowPrerelease switch should not be required, as the user has already specified a "beta" version.

**Comment by Jaykul** [comment]
Please, no. This module is _too cautious_. This isn't a graphical installer for children, that's going to pop up an elevation prompt where dad has to come over and authenticate that they have permission to install things...

If people are specifying a version number on the command line they **either** 
1. know what they're doing, or 
2. are copy-pasting code off the internet 

**In either case, you should not try to "save" them.**

I know that there's no _real_ harm in outputting a message, but using _warnings_ and _errors_ when you're doing what the user asked for is frustrating and contributes to overall numbing of people against actually important warnings. In fact, it might result in people putting instructions on GitHub that hide _that_ warning, but inadvertently hide much more important warnings too ...

```PowerShell
Install-Module Foo -Require 1.2.0-beta001 -wa 0
```

At the end of the day, "pre-release" means *whatever* the developer of the module says it means, and **there's ZERO GUARANTEE that non-prerelease modules aren't going to "break your system"** -- PowerShellGet _literally_ has no idea what it's "protecting" people from.

It's even possible that someone could publish a pre-release like `10.0.0-goldmaster` instead of the normal `1.2.3-beta#` or `1.2.3-rc#` or --_if it's Microsoft_-- `1.2.3-pre####` ... but the bottom line is that if people are putting a specific version into the command, they are not _guessing_, they have **looked up a specific version**, and consciously made the decision to install it. A warning serves no purpose.

**Comment by SydneyhSmith** [comment]
Can confirm that this issue has not been resolved.

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
