### ISSUE TITLE
Publish-PSResource: complete unimplemented parameter sets/parameters

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#469]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

n/a

### Expected behavior

```console
be implemented
```

### Actual behavior

```console
not yet implemented
```

### Error details

```console
-add Name parameter [rejected]
-add DestinationPath parameter [completed]
-add Nuspec parameter (discuss with Paul) [rejected]
```

### Environment data

```powershell
all
```

**Comment by SydneyhSmith** [comment]
For now we will focus on the -Name and -DestinationPath parameters and will hold off on the -nuspec parameter

**Comment by alerickson** [comment]
After discussion with @PaulHigin, we've decided to hold off on implementing the -Name parameter because the discovery process ([outlined in the v2 docs here](Specifies the name of the module that you want to publish. Publish-Module searches for the specified module name in $Env:PSModulePath.)) is a bit confusing and can easily lead to accidental publishing of modules. 

For now, we will leave this intentionally unimplemented and if there's community requests to have a -Name parameter we can open up discussion on how best to discover the package to be published.
