### ISSUE TITLE
PowerShellGet v3 beta version change potential issues when GA is released

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#479]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

The previous v3 beta versions were in the format of `3.0.0-betaX` this has now changed to `3.0.X-beta` with the first to take this change of `3.0.11-beta`. The potential problem with this version change is that when `3.0.0` stable is released. If people use `Update-PSResource -Name PowerShellGet -Prerelease`. The user would expect to upgrade to the latest prerelease but what would really happen is that the user would be downgraded to 3.0.0 a prerelease version. Here is what would happen 3.0.0 stable is "older" then 3.0.11-beta. This change seems not to be a fluke in release versions since the tag for the next release is `3.0.12-beta`. To mitigate this issue the first stable version of PowerShellGet v3 would need to be something higher than the latest "beta" release. Something like `3.1.0` which is not really ideal. Why was this change made in the first place?

### Expected behavior

```console
3.0.0-beta11
```

### Actual behavior

```console
3.0.11-beta
```

### Environment data

```powershell
3.0.11-beta
```

**Comment by StevenBucher98** [comment]
Thanks @ThomasNieto! PowerShell does not support semantic versioning for prerelease tags so a user would not be able to upgrade from 3.0.0-beta1 to 3.0.0-beta2 for example because PowerShellGet truncates the prerelease tag when it installs the prerelease version. Having the new betas in the patch version fixes this issue for beta/preview users. It makes it easier for users to upgrade from one beta release to newer beta without having to uninstall the older one. We do eventually plan to support semantic versioning in PowerShell but in the meantime we are doing this work around.

As for the GA we plan for that release's version to be 3.1.0. We know this is not ideal and is slightly awkward, if we thought about this scenario earlier on, we would have had the beta releases be 2.9.x-beta.

**Comment by ThomasNieto** [comment]
@StevenBucher98 this has been a known defect of PowerShellGet for a long time since v2 https://github.com/PowerShell/PowerShellGet/issues/78 that you cannot upgrade a prerelease module with binary components. Is this not going to be fixed with 3.0.0 GA? Plus I expect the Semantic Versioning support would really need to be added in 7.2 GA for PowerShellGet v3 to make use of it without having to wait another year. If the PS team is going add support for Semantic Versioning can you please update the team's intention on https://github.com/PowerShell/PowerShell/issues/2983?

Even if PowerShell and PoweShellGet adds support for semantic versioning how would PS 5.1 be handled?

**Comment by StevenBucher98** [comment]
Thanks @ThomasNieto,

>  Is this not going to be fixed with 3.0.0 GA?

No, we need to wait for semantic versioning to be added to PowerShell first. This change would not make it until 7.3 so it would be a while before PowerShellGet v3 to have full integration with it. Unfortunately, this may not happen for another year; it is something we are trying to get done as quickly as feasibly possible.  

As for backwards compatibility, that is something we will address once semantic versioning is fixed. We have created an issue to begin discussions around potential problems and concerns. [#484](https://github.com/PowerShell/PowerShellGet/issues/484)

**Comment by ThomasNieto** [comment]
No longer an issue now that the module has a new name.
