### ISSUE TITLE
Register-PSResourceRepository should support -Force

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#612]
### Summary of the new feature / enhancement

As a devops engineer, I want to be able to configure PSRepositories in a _somewhat declarative_ Register-or-Set way, particularly during automation runs.

```PowerShell
$Repositories = <# import a list from a psd1 file #> @{
    Name = "OurGallery"
    Url = "https://proget.OurDomain.com/nuget/PowerShell"
    Trusted = $true
    Priority = 90
}
Register-PSResourceRepository -Repositories $Repositories
```

## The problem

Currently, if the repository exists, `Register` fails, and I must use `Set` but although I can use the *same syntax* with `Set-PSResourceRepository`, in this case, if the repository does not _already_ exist, it fails.

So I have to:

1. Clear out existing registrations
2. **Separately** re-register the PSGallery correctly
3. Then register the **other** repositories we use

```PowerShell
@('PSGallery') + $Repositories.Name | Unregister-PSResourceRepository
Register-PSResourceRepository -PSGallery -Priority 10 
Register-PSResourceRepository -Repositories $Repositories
```

Or I have to:

1. Put the PSGallery into my config file *without* the URL
2. **Separately** re-register the PSGallery
3. `Register` **and** `Set` all the repositories, ignoring the errors

```PowerShell
Register-PSResourceRepository -PSGallery
Register-PSResourceRepository -Repositories $Repositories -ErrorAction SilentlyContinue -ErrorVariable Failed
if ($Failed) {
Set-PSResourceRepository -Repositories $Repositories
}
```

### Proposed technical implementation details

I'd like a `-Force` switch on either Register or Set that would overwrite existing repositories (in the case of Register) or register them (in the case of Set) so that I can have declarative Register-or-Set syntax for the set of repositories I need, without needing the extra separate call to fix PSGallery, and the extra call to unregister the repositories before re-registering them (or set them after failing to register them)...

**Comment by StevenBucher98** [comment]
Thanks @Jaykul! Thats a good idea, we will look at adding it into `Register-PSRespository`. 

Adding a note here for us to remember how this will work with the credential persistence.

**Comment by StevenBucher98** [comment]
@Jaykul what do you think about having this proposed parameter as `-AllowClobber` instead of `-Force`?

**Comment by Jaykul** [comment]
I can live with that @StevenBucher98 -- well, for `Register` anyway. For `Set` I think it would need to be `-Force` or `-AllowNew` 😉.

**Comment by tristanbarcelon** [comment]
> I can live with that @StevenBucher98 -- well, for `Register` anyway. For `Set` I think it would need to be `-Force` or `-AllowNew` 😉.

@Jaykul, did you mean `Register-PSRepository` instead of `Register-PSResourceRepository`? Seems like we're both trying to solve the same thing, which is to initialize PSRepository with private feeds on top of the default PSGallery. I encountered  #611 with PowershellGet and https://github.com/PowerShell/PowerShellGetv2/issues/661 with PowershellGetV2 which I'm hoping to address/sidestep by storing the PSRepositories.xml file in a keyvault and using it to overwrite the local repository at the beginning of each azure devops pipeline job. The exact location of PSRepositories.xml is defined here https://github.com/PowerShell/PowerShellGetv2/blob/master/src/PowerShellGet/private/modulefile/PartOne.ps1 so my workaround will be coupled to Microsoft's implementation details. I'm resorting to this method since I don't have any ETA when these issues will be fixed and we need to decouple our pipeline jobs from PSGallery outages. Do you think this is a good idea?

We do have a separate job running daily which synchronizes PSGallery modules we depend on to a private Azure Devops feed.

**Comment by Jaykul** [comment]
@tristanbarcelon there hasn't been any point filing issues about PSGetv2 **for years** --they won't even accept PRs to fix things-- because v3 will be out "soon." But yes, we had this problem with PSGetv2 and I went looking to see if it was still a problem in v3 😉 and ... here we are.

**Comment by ThomasNieto** [comment]
The parameter for `Register-PSResourceRepository` should be called `Force` as the meaning is clear and concise and is consistent with other core cmdlets. The only time `Force` is a problem is when the meaning is not instantly clear to the end user. In this case there is no question what force does. If you _really_ need it to be `AllowClobber` then `Force` should be added as an alias.

As for `Set-PSResourceRepository` it should set existing repository values or create a new repository if it doesn't exist without any additional switch parameters.

The reason for this behavior is that it matches existing core cmdlets and documentation. For example, the [PowerShell Verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.2#new-vs-set) has this to say about `New` vs `Set`. In this case `Register` is equivalent to `New`.

> Use the New verb to create a new resource. Use the Set verb to modify an existing resource, optionally creating it if it does not exist, such as the Set-Variable cmdlet.
