### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by hbuckle** [PowerShell/PSResourceGet#629]
### Summary of the new feature / enhancement

Development here has been going on for ages, any chance of getting it finished and released any time soon?

**Comment by SydneyhSmith** [comment]
Thanks so much for opening this issue @hbuckle we do not have a release date as this is a quality rather than date driven project. Totally understand the frustration with the speed of development-- I too am super excited for this to release! We are focusing internally on how we can accelerate towards the finish line on this project. Everything we are working on is openly available in this repo so you can have a window into our development process.
