### ISSUE TITLE
Build pipeline is failing with No repository found

### ISSUE THREAD

**Issue by soundd2** [PowerShell/PSResourceGet#644]
I tried to build pipeline but it is failing with following error
![image](https://user-images.githubusercontent.com/94822959/166445069-5aac931b-ba44-437c-94a1-dfead58d2d88.png)
I tried to troubleshoot with following commands mentioned in the below screenshot. Please help
![image](https://user-images.githubusercontent.com/94822959/166445142-cb9e10b3-995d-486f-9956-754cf4fa7638.png)

Logs:
![image](https://user-images.githubusercontent.com/94822959/166445204-14fdca6f-5e2b-4015-8c4f-104a77ffd42a.png)

**Comment by SydneyhSmith** [comment]
@soundd2 thanks for opening this issue, what happens when you run `Get-PSRepository`? Also it looks like the install of PowerShellGet is successful, are you able to confirm this with a `Get-Module PowerShellGet -ListAvailable` call? Also curious why you are choosing 2.2.4 over the latest available (2.2.5)?

**Comment by soundd2** [comment]
Hi Syndey Smith,

I could resolve the issue by executing following commands 
![image](https://user-images.githubusercontent.com/94822959/167072927-1a0ff71a-e809-4d3f-9551-a7a7b40d3ac2.png)
