### ISSUE TITLE
Allow 3rd-Party CredentialProviders

### ISSUE THREAD

**Issue by stevek** [PowerShell/PSResourceGet#68]
Currently Get-CredsFromCredentialProvider.ps1 is hard-wired to only allow CredentialProviders for pkgs.dev.azure.com and pkgs.visualstudio.com.  To enable a 3rd party to write their own credential provider:

- remove lines 17-23 in that file

or

- provide a means to customize the sanity check
- provide a way to point to a custom CredentialProvder.

**Comment by Darsstar** [comment]
Since I was wondering myself, this seems to be the current status of things: [In PowerShellGet 3.0 preview 14 the -CredentialInfo parameter was added](https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-14/) which interacts with [SecretManagement](https://devblogs.microsoft.com/powershell/announcing-secretmanagement-1-1-ga/).

**Comment by SydneyhSmith** [comment]
Closing this issue as resolved in PSResourceGet
