### ISSUE TITLE
Change the name of cmdlets to not conflict with V2

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#919]
### Summary of the new feature / enhancement

Update the following cmdlets so that the names do not conflict with the names in PSGet v2.  We need this in order to ship PSGet v3 side by side with v2 in PowerShell.

Get-PSResource                ->  Get-InstalledPSResource
New-PSScriptFileInfo        ->  New-PSScriptFile
Test-PSScriptFileInfo         ->  Test-PSScriptFile

**Comment by ThomasNieto** [comment]
`Get-PSResource` does not conflict with any v2 cmdlets. Plus I logged a ticket #457 when this cmdlet was called `Get-InstalledPSResource` to this `Get-PSResource` as "installed" is redundant and unnecessary.

**Comment by anamnavi** [comment]
We had an internal discussion about this, and want to make it analogous to V2 cmdlets where we have Get-InstalledModule (from the PSGet side) and Get-Module (from PowerShell side) and reduce confusion between their different outputs. Get-InstalledModule (and in V3 Get-InstalledPSResource) would get resources installed via PowerShellGet on your machine, not all of them as Get-Module does. We will also look into an alias for the command.

**Comment by ThomasNieto** [comment]
There is no overlap/confusion between Get-Module and Get-PSResource because the noun has changed to PSResource. So why are we trying to keep the v2 convention with "Installed" as a prefix? I'm trying to understand the reasoning as "Installed" is redundant as it's already implied that it's installed on the system with the Get verb. If it wasn't already installed or locally present on the system then it would have a different verb.

**Comment by ThomasNieto** [comment]
In regard to cmdlet naming and having v2 and v3 without name conflicts you're missing `Update-ScriptFileInfo` and `Update-ModuleManifest`. It would be the right time to fix the verbs in addition to changing the noun as I mention in #766 to `Set`.
